.text
.align	4
.globl	x_trampo
x_trampo:
	mov	sp  , x1
	mov x30 , x0

	mov	x0,0
	mov x1,x0
	mov	x2,x0
	mov	x3,x0
	mov	x4,x0
	mov	x5,x0
	mov	x6,x0
	mov	x7,x0
	mov	x8,x0
	mov	x9,x0
	mov	x10,x0
	mov	x11,x0
	mov	x12,x0
	mov	x13,x0
	mov	x14,x0
	mov	x15,x0
	mov	x16,x0
	mov	x17,x0
	mov	x18,x0
	mov	x19,x0
	mov	x20,x0
	mov	x21,x0
	mov	x22,x0
	mov	x23,x0
	mov	x24,x0
	mov	x25,x0
	mov	x26,x0
	mov	x27,x0
	mov	x28,x0
	mov	x29,x0
	
	ret